keys:
  - &jester age1frleydx230mxmva5qu2ql2gtaczsganzc9ty08yscj7gcn2z0css5xypxh
  - &yasha age1y6ak685rjpttkz09grxldfkxtwd466cg7msrlk67yjeslkde3dqqefcfx9
creation_rules:
  - path_regex: '.*\.(yaml|env)$'
    key_groups:
    - age:
      - *jester
      - *yasha
    
